"""
File with Hangman diagrams for incorrect guesses 
"""
def hangman(guesses):
    if (guesses == 0):
        print("  ________")
        print("   |/      ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 1):
        print("  ________")
        print("   |/    |")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 2):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 3):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 4):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |    /| ")
        print("   |        ")
        print("   |        ")
        print("   |       ")
        print("   ======")
    elif (guesses == 5):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |    /|\\")
        print("   |       ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 6):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |    /|\\")
        print("   |     | ")
        print("   |       ")
        print("   |       ")
        print("   ======")
    elif (guesses == 7):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |    /|\\")
        print("   |     | ")
        print("   |    /  ")
        print("   |       ")
        print("   ======")
    elif (guesses == 8):
        print("  ________")
        print("   |/    |")
        print("   |     O")
        print("   |    /|\\")
        print("   |     | ")
        print("   |    / \\")
        print("   |       ")
        print("   ======")

